require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-graphql

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable

Metrics/BlockLength: 
  Exclude:
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

GraphQL/ExtractType:
  Enabled: false